-- drop table if exists users cascade;
-- create table users
-- (
--     id            bigserial       not null
--         constraint users_pkey
--             primary key,
--     date_of_birth date         not null,
--     email         varchar(255) not null
--         constraint uk_6dotkott2kjsp8vw4d0m25fb7
--             unique
-- );
--
-- drop table if exists accounts cascade;
-- create table accounts
-- (
--     deposit_eur numeric(12, 2) not null,
--     deposit_usd numeric(12, 2) not null,
--     user_id     bigint         not null
--         constraint accounts_pkey
--             primary key
--         constraint fknjuop33mo69pd79ctplkck40n
--             references users
--             on delete cascade
-- );
--
--
-- drop table if exists passports cascade;
-- create table passports
-- (
--     id              bigserial       not null
--         constraint passports_pkey
--             primary key,
--     address         varchar(255) not null,
--     name            varchar(255) not null,
--     passport_number varchar(255) not null
--         constraint uk_69bfsj94jasugfvkufhe2rcbv
--             unique,
--     surname         varchar(255) not null,
--     user_id         bigint       not null
--         constraint fkbxf1dmm0wl2hf7c9pxggl4jcy
--             references users
-- );
--
--
-- drop table if exists bills cascade;
-- create table bills
-- (
--     id      bigserial         not null
--         constraint bills_pkey
--             primary key,
--     amount  numeric(10, 2) not null,
--     date    date           not null,
--     car_id  bigint         not null
--         constraint fkca6qp8h7nywor437hfrws1t6b
--             references cars,
--     user_id bigint         not null
--         constraint fkk8vs7ac9xknv5xp18pdiehpp1
--             references users
-- );
--
-- drop table if exists cars cascade;
-- create table cars
-- (
--     id                  bigserial       not null
--         constraint cars_pkey
--             primary key,
--     mileage             integer      not null,
--     model               varchar(255) not null,
--     production_date     date         not null,
--     registration_number varchar(255) not null
--         constraint uk_i3ldfyekqw49cw6omv99rrfkx
--             unique
-- );
--
--
-- drop table if exists trips cascade;
-- create table trips
-- (
--     user_id bigint not null
--         constraint fk8wb14dx6ed0bpp3planbay88u
--             references users,
--     cars_id bigint not null
--         constraint fkk0enxtl36yvtlaynly8mbjcso
--             references cars,
--     constraint trips_pkey
--         primary key (user_id, cars_id)
-- );
